project:
  type: website
  output-dir: docs

website:
  title: "Salva's website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: Resume
      - href: software.qmd
        text: Software
      - href: talks.qmd
        text: Talks and Workshops
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual