project:
  type: website
  output-dir: docs

website:
  title: "Salva's website"
  open-graph: true
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: Resume
      - href: portfolio.qmd
        text: Portfolio
    right:
      - icon: github
        href: https://github.com/salvafern
      - icon: twitter
        href: https://twitter.com/salvafern
      - icon: linkedin
        href: https://www.linkedin.com/in/salvafernandez/
  page-footer: 
    center: '<small>© Salvador Fernández 2023</small>'
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

